<?php
/**
 * Created by PhpStorm.
 * User: jonaskortum
 * Date: 24.07.17
 * Time: 11:27
 */

function delphi_question_menu() {

    $items['add_questions/%'] = array(
        'page callback' => 'drupal_get_form',
        'access callback' => 'user_is_logged_in',
        'page arguments' => array('delphi_question_add_question_form'),
        'file' => 'delphi_question_add_question.inc'
    );

    $items['change_question/%/%'] = array(
        'page callback' => 'drupal_get_form',
        'access callback' => 'user_is_logged_in',
        'page arguments' => array('delphi_question_change_question_form'),
        'file' => 'delphi_question_change_question.inc'
    );

    $items['question_overview'] = array(
        'page callback' => 'drupal_get_form',
        'access callback' => 'user_is_logged_in',
        'page arguments' => array('delphi_question_question_overview_form'),
        'file' => 'delphi_question_overview.inc'
    );

    $items['delete_question/%'] = array(
        'access callback' => 'user_is_logged_in',
        'page callback' => 'delphi_question_delete_question',
        'file' => 'delphi_question_overview.inc'
    );

    return $items;
}

