<?php
/**
 * Created by PhpStorm.
 * User: jonaskortum
 * Date: 16.02.17
 * Time: 10:21
 */

require_once("survey_question_evaluation.inc");


function survey_menu()
{

    $items['start_survey'] = array(
        'title' => 'Umfrage starten',
        'page callback' => 'drupal_get_form',
        'access callback' => 'user_is_logged_in',
        'page arguments' => array('survey_start_form'),
    );

    $items['survey_question/%/%'] = array(
        'page callback' => 'drupal_get_form',
        'access callback' => TRUE,
        'page arguments' => array('survey_form'),
        'file' => 'survey_answer_question.inc'
    );

    $items['survey_question_evaluation/%/%'] = array(
        'page callback' => 'drupal_get_form',
        'access callback' => TRUE,
        'page arguments' => array('survey_question_evaluation_form'),
        'file' => 'survey_question_evaluation.inc'
    );

    $items['finish_survey/%'] = array(
        'title' => 'Ende der Umfrage',
        'access callback' => 'user_is_logged_in',
        'page callback' => 'survey_finish_survey',
    );

    $items['survey/tokens'] = array(
      'page callback' => 'drupal_get_form',
      'access arguments' => array('administer users'),
      'page arguments' => array('survey_token_form'),
    );

    $items['survey/configure'] = array(
      'page callback' => 'drupal_get_form',
      'access arguments' => array('administer users'),
      'page arguments' => array('survey_configure_form'),
      'file' => 'survey_configure.inc'

    );

    $items['survey/tokens/download'] = array(
      'title' => t('Zugangsschlüssel CSV Export'),
      'page callback' => '_survey_token_csv_export_callback',
      'type' => MENU_CALLBACK,
      'access arguments' => array('administer users'),
    );

    $items['survey/%'] = array(
      'title' => 'Umfrage starten',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('survey_start_form'),
      'access callback' => TRUE,
      );

    return $items;
}

//Diese Funktion baut die Startseite der Umfrage
function survey_start_form($form, &$form_state)
{
  $survey = _survey_get_survey(1);

  drupal_set_title(check_plain($survey['title']));

  $form['welcome'] = array(
    '#markup' => $survey['welcome_msg'],
  );


  // user token is null if an admin uses internal start survey
  $userToken = arg(1);
  if (!is_null($userToken)) {
    if(count(_survey_get_answered_questions($userToken)) > 0) {
      // get the ID of first unanswered question
      $questionId = _survey_get_first_open_question(arg(1));

      // -1 = all questions have been answered
      if ($questionId !== -1) {
        $form['continue'] = array(
          '#type' => 'submit',
          '#value' => t('Umfrage fortführen'),
          '#submit' => array('survey_continue_survey')
        );

        $form_state['#continue_qid'] = $questionId;
        $form_state['#continue_uid'] = $userToken;
      }
    }
  }

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Umfrage starten',
    '#submit' => array('survey_start_survey')
  );

  return $form;
}

function survey_continue_survey($form, &$form_state) {
  $path = "survey_question/" . $form_state['#continue_qid'] . "/" . $form_state['#continue_uid'];
  $form_state['redirect'] = $path;
}

/*
 * Diese Funktion führt den Nutzer zurück ins Hauptmenü
 */
function survey_finish_survey()
{
  $survey = _survey_get_survey(1);
  return $survey['end_msg'];
}

/*
 * Diese Funktion lädt alle verfügbaren Fragen der Umfrage aus der Datenbank und sortiert sie aufsteigend nach
 * Benutzer-Gewichtung und der ID
 */
function survey_get_all_questions()
{
    $questions = array();
    $question_result = db_query("SELECT * FROM {question} ORDER BY weight, question_id");

    foreach ($question_result as $question) {
        array_push($questions, $question);
    }

    return $questions;
}

/*
 * Diese Funktion ermittelt alle verfügbaren Antwortmöglichkeiten einer Frage und gibt sie sortiert nach der ID
 * aufsteigend zurück. Die ID der entsprechenden Frage wird als Parameter übergeben
 */
function survey_get_answers_from_question($question_id)
{
    $answers = array();
    $answer_result = db_query("SELECT * FROM {question_possible_answers} WHERE question_id = :question_id ORDER BY weight", array(
        'question_id' => $question_id
    ));
    foreach ($answer_result as $answer) {
        array_push($answers, $answer);
    }

    return $answers;
}


//Diese Funktion startet die Umfrage. Es wird ein einzigartiges Passwort für den Nutzer erstellt und in die DB
//geschrieben. Anschließend wird der Nutzer zur ersten Frage weitergeleitet.
function survey_start_survey()
{
    if(arg(0) === 'survey') {
      $user_check_string = arg(1);
    } else {
      $user_check_string = survey_create_token();
    }

    //Die erste Frage wird geladen
    $question_id = survey_get_questions(0);
    drupal_goto("survey_question/" . $question_id . "/" . $user_check_string);
}

//Diese Funktion generiert eine einzigartige ID für jeden Nutzer die 30 Stellen beinhaltet.
function survey_generate_random_string($length)
{
    $valid_characters = '0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ';
    $characters_length = strlen($valid_characters);
    $random_string = '';
    for ($i = 0; $i < $length; $i++) {
        $random_string .= $valid_characters[rand(0, $characters_length - 1)];
    }
    return $random_string;
}

/**
 * Generates and saves a unique user token.
 *
 * @return string
 *   The generated unique user token.
 */
function survey_create_token() {
  //Einzigartige ID für den Nutzer wird angelegt...
  do {
    $user_check_string = survey_generate_random_string(30);
    $success = true;

    //...und abgespeichert
    try {
      db_query("INSERT INTO {survey_users} (user_pw) VALUES (:user_pw)", array(
        ':user_pw' => $user_check_string
      ));
    } catch (PDOException $e) {
      // generated token already used, try again
      $success = false;
    }
  } while (!$success);

  return $user_check_string;
}


/**
 * @param $token
 *   Unique string user token.
 *
 * @return string
 *   Full link to the survey.
 */
function survey_get_survey_link($token) {
  global $base_url;
  $link = check_plain($base_url . '/survey/' . $token);

  return $link;
}


/**
 * Builds the form to manage survey participants / tokens.
 */
function survey_token_form($form, &$form_state) {
  if (empty($form_state['values']['token_quantity'])) {
    // form to create new tokens
    $form['token_quantity'] = array(
      '#type' => 'textfield',
      '#title' => "Zugangsschlüssel",
      '#title_display' => 'invisible',
      '#size' => 1,
      '#maxlength' => 3,
      '#element_validate' => array('element_validate_integer_positive'),
      '#field_suffix' => t('Zugangsschlüssel für Umfrageteilnehmer erstellen.'),
    );

    $form['submit'] = array(
      '#type' => 'submit',
      '#value' => 'Zugangsschlüssel erstellen',
    );

  } else {
    // table with created tokens and full survey links.
    $noTokens = $form_state['values']['token_quantity'];
    $count = 1;

    $header = array(t('Zugangsschlüssel'), t('Umfrage-URL'));
    $rows = array();
    while ($count <= $noTokens) {
      $token = survey_create_token();
      $rows[] = array(
        'token' => $token,
        'link' => survey_get_survey_link($token)
      );
      $count++;
    }

    $form['tokens_table'] = array (
      '#theme' => 'table',
      '#header' => $header,
      '#rows' => $rows,
      '#title' => t('Zugangsschlüssel'),
    );

    $form['csv_submit'] = array(
      '#type' => 'submit',
      '#value' => t('Zugangsschlüssel als CSV exportieren'),
      '#submit' => array('_survey_token_csv_export_callback'),
    );
  }

  return $form;
}

function survey_token_form_submit($form, &$form_state) {
  $form_state['rebuild'] = true;
}

/**
 * Exports survey links as a csv file.
 * @see http://drupalpeople.com/blog/output-data-csv-file-drupal-download
 */
function _survey_token_csv_export_callback($form, &$form_state) {
  // add necessary headers for browsers
  drupal_add_http_header('Content-Type', 'text/csv; utf-8');
  drupal_add_http_header('Content-Disposition', 'attachment; filename = survey_tokens.csv');

  //instead of writing down to a file we write to the output stream
  $fh = fopen('php://output', 'w');

  //form header
  fputcsv($fh, array(t('Token'), t('Link')));

  //write data in the CSV format
  foreach ($form['tokens_table']['#rows'] as $row) {
    fputcsv($fh, array($row['token'], $row['link']));
  }

  //close the stream
  fclose($fh);
  drupal_exit();
}


//Diese Funktion holt sich die zuletzt abgegebenen Antworten eines Nutzers zu einer bestimmten Frage aus der DB und gibt
//diese als Array zurück.
function survey_get_answers($question_id, $user_passcode)
{
    $answers = array();

    //Antworten eines Nutzers zu einer Frage werden geladen
    $answer_result = db_query("SELECT * FROM {question_user_answers} WHERE user_pw = :user_pw AND question_id = :question_id
                              ORDER BY question_user_answers_id ASC", array(
        ':user_pw' => $user_passcode,
        ':question_id' => $question_id
    ));

    foreach ($answer_result as $answer) {
        // Nur die zuletzt abgegebene Antwort zurückgeben.
        $answers[$answer->answer_id] = $answer;
    }

    return $answers;

}

//Diese Funktion überprüft, ob die eingelesene Nutzer-ID aus der Taskleiste valide ist.
function survey_check_valid_user_pw($user_pw)
{

    $counter = 0;
    $result = db_query("SELECT * FROM {survey_users} WHERE user_pw = :user_pw", array(
        ':user_pw' => $user_pw
    ));

    foreach ($result as $item) {
        $counter++;
    }

    if ($counter == 1) {
        return true;
    } else {
        return false;
    }
}

//Diese Funktion sucht sich anhand der aktuellen Fragen-ID die nächste Frage aus der DB und gibt diese zurück. Sollte
//keine Frage mehr folgen, wird eine -1 zurückgegeben.
function survey_get_questions($current_question_id)
{

    $questions = array();
    $question_result = db_query("SELECT * FROM {question} ORDER BY weight, question_id");

    foreach ($question_result as $question) {
        array_push($questions, $question->question_id);
    }

    $question_index = array_search($current_question_id, $questions);

    if (sizeof($questions) > $question_index) {
        return $questions[$question_index];
    } else {
        return -1;
    }
}

/**
 * Überprüft, ob es sich bei der Benutzereingabe um eine nichtnegative Ganzzahl handelt.
 * Wurde 'keine Angabe' ausgewählt wird dies als -99999 codiert gespeichert.
 *
 * @param $element
 *   Das zu überprüfende Form-Element
 */
function survey_element_validate_nonnegative_integer(&$element, &$form_state) {
  $value = $element['#value'];

  // extract the ID of the textfield to be validated to check the associated 'k. A.' checkbox
  $elementId = intval(preg_replace('/[^0-9]+/', '', $element['#name']), 10);

  if ($form_state['values']['quantity_check' . $elementId] === 1) {
    form_set_value($element, -99999, $form_state);
    $element['#value'] = -99999;
  } else if ($value !== '' && (!is_numeric($value) || intval($value) != $value || $value < 0)) {
    form_error($element, t('%name must be an non-negative integer.', array(
      '%name' => $element['#title'],
    )));
  } else if ($value === '') {
    form_error($element, t('Das Feld %name ist erforderlich.', array(
      '%name' => $element['#title'],
    )));
  }
}

/**
 * Returns the type of a question.
 *
 * @param $questionId
 *  The question ID to be looked up.
 *
 * @return string
 *  The question type or -1 if the query failed.
 */
function _survey_get_question_type($questionId) {
  $type = '';
  try {
    $result = db_query("SELECT type FROM {question} WHERE question_id = :question_id", array(
      'question_id' => $questionId,
    ));
    $type = $result->fetchField();

  } catch (PDOException $e) {
    $type = 'error';
  }

  return $type;
}

/**
 * Returns the survey configuration data.
 *
 * @param $surveyId
 *  The survey ID to be looked up.
 *
 * @return array
 *  Associative array of the survey data.
 */
function _survey_get_survey($surveyId) {
  try {
    $result = db_query("SELECT * FROM {survey} WHERE sid = :surveyId", array(
      'surveyId' => $surveyId,
    ));
    $survey = $result->fetchAssoc();

  } catch (PDOException $e) {
    $survey = array();
  }

  return $survey;
}

/**
 * Returns the first question the user did not answer.
 *
 * @param $userToken
 *  The unique user token.
 *
 * @return int
 *  The ID of the user's first unanswered question or -1 if all questions have been answered or -2 if an error occured.
 */
function _survey_get_first_open_question($userToken) {
  try {
    $result = db_query("
      SELECT q.question_id FROM {question} as q
      LEFT OUTER JOIN 
        (SELECT question_id FROM {question_user_answers}
          WHERE user_pw = :userToken
          GROUP BY question_id
        ) as answer
      ON q.question_id = answer.question_id
      WHERE answer.question_id IS null
      ORDER BY q.weight ASC
      LIMIT 1", array(
        'userToken' => $userToken,
    ));

    $questionID = $result->fetchField(0);

    // false if all questions have been answered
    if ($questionID === FALSE) {
      $questionID = -1;
    }
  } catch (PDOException $e) {
    $questionID = -2;
  }

  return $questionID;
}

/**
 * Returns all answered questions of a user.
 *
 * @param $userToken
 *   The unique user token.
 *
 * @return array
 *   Associative array of all answered quesstions.
 */
function _survey_get_answered_questions($userToken) {
  $answeredQuestions = array();
  try {
    $result = db_query("
      SELECT question_id FROM {question_user_answers}
      WHERE user_pw = :userToken
      GROUP BY question_id", array(
        'userToken' => $userToken,
    ));

    $answeredQuestions = $result->fetchAllAssoc('question_id');

  } catch (PDOException $e) {
    $answeredQuestions = array();
  }

  return $answeredQuestions;
}

/**
 * Builds a status bar indicating how many questions have already been answered.
 *
 * @param $userToken
 *   The unique user token.
 *
 * @return string
 *   HTML code of the user's survey progress bar.
 */
function _survey_get_status_bar($userToken) {
  $questionsCount = count(survey_get_all_questions());
  $answeredCount = count(_survey_get_answered_questions($userToken));

  $progressPercent = $answeredCount / $questionsCount * 100;

  $html = '';
  $html .= '<div class="progress-bar">';
  $html .= '<div class="progress" style="width: ' . $progressPercent . '%">' . round($progressPercent) . '%</div></div>';

  return $html;
}