<?php
/**
 * Created by PhpStorm.
 * User: jonaskortum
 * Date: 16.02.17
 * Time: 10:21
 */

require_once("survey_question_evaluation.inc");


function survey_menu()
{

    $items['start_survey'] = array(
        'title' => 'Umfrage starten',
        'page callback' => 'drupal_get_form',
        'access callback' => 'user_is_logged_in',
        'page arguments' => array('survey_start_form'),
    );

    $items['survey_question/%/%'] = array(
        'page callback' => 'drupal_get_form',
        'access callback' => 'user_is_logged_in',
        'page arguments' => array('survey_form'),
        'file' => 'survey_answer_question.inc'
    );

    $items['survey_question_evaluation/%/%'] = array(
        'page callback' => 'drupal_get_form',
        'access callback' => 'user_is_logged_in',
        'page arguments' => array('survey_question_evaluation_form'),
        'file' => 'survey_question_evaluation.inc'
    );

    $items['finish_survey/%'] = array(
        'title' => 'Ende der Umfrage',
        'access callback' => 'user_is_logged_in',
        'page callback' => 'survey_finish_survey',
    );

    return $items;
}

//Diese Funktion baut die Startseite der Umfrage
function survey_start_form()
{
    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'Start',
        '#submit' => array('survey_start_survey')
    );

    return $form;
}

/*
 * Diese Funktion führt den Nutzer zurück ins Hauptmenü
 */
function survey_finish_survey()
{
    return "Danke für Ihre Teilnahme, die Umfrage ist nun beendet!";
}

/*
 * Diese Funktion lädt alle verfügbaren Fragen der Umfrage aus der Datenbank und sortiert sie nach der ID
 * aufsteigend
 */
function survey_get_all_questions()
{
    $questions = array();
    $question_result = db_query("SELECT * FROM {question} ORDER BY question_id");

    foreach ($question_result as $question) {
        array_push($questions, $question);
    }

    return $questions;
}

/*
 * Diese Funktion ermittelt alle verfügbaren Antwortmöglichkeiten einer Frage und gibt sie sortiert nach der ID
 * aufsteigend zurück. Die ID der entsprechenden Frage wird als Parameter übergeben
 */
function survey_get_answers_from_question($question_id)
{
    $answers = array();
    $answer_result = db_query("SELECT * FROM {question_possible_answers} WHERE question_id = :question_id ORDER BY answers_id", array(
        'question_id' => $question_id
    ));
    foreach ($answer_result as $answer) {
        array_push($answers, $answer);
    }

    return $answers;
}


//Diese Funktion startet die Umfrage. Es wird ein einzigartiges Passwort für den Nutzer erstellt und in die DB
//geschrieben. Anschließend wird der Nutzer zur ersten Frage weitergeleitet.
function survey_start_survey()
{
    //Einzigartige ID für den Nutzer wird angelegt...
    $user_check_string = survey_generate_random_string(30);

    //...und abgespeichert
    db_query("INSERT INTO {survey_users} (user_pw) VALUES (:user_pw)", array(
        ':user_pw' => $user_check_string
    ));

    //Die erste Frage wird geladen
    $question_id = survey_get_questions(0);
    drupal_goto("survey_question/" . $question_id . "/" . $user_check_string);
}

//Diese Funktion generiert eine einzigartige ID für jeden Nutzer die 30 Stellen beinhaltet.
function survey_generate_random_string($length)
{
    $valid_characters = '0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ';
    $characters_length = strlen($valid_characters);
    $random_string = '';
    for ($i = 0; $i < $length; $i++) {
        $random_string .= $valid_characters[rand(0, $characters_length - 1)];
    }
    return $random_string;
}

//Diese Funktion holt sich die zuletzt abgegebenen Antworten eines Nutzers zu einer bestimmten Frage aus der DB und gibt
//diese als Array zurück.
function survey_get_answers($question_id, $user_passcode)
{
    $answers = array();

    //Antworten eines Nutzers zu einer Frage werden geladen
    $answer_result = db_query("SELECT * FROM {question_user_answers} WHERE user_pw = :user_pw AND question_id = :question_id
                              ORDER BY question_user_answers_id ASC", array(
        ':user_pw' => $user_passcode,
        ':question_id' => $question_id
    ));

    foreach ($answer_result as $answer) {
        // Nur die zuletzt abgegebene Antwort zurückgeben.
        $answers[$answer->answer_id] = $answer;
    }

    return $answers;

}

//Diese Funktion überprüft, ob die eingelesene Nutzer-ID aus der Taskleiste valide ist.
function survey_check_valid_user_pw($user_pw)
{

    $counter = 0;
    $result = db_query("SELECT * FROM {survey_users} WHERE user_pw = :user_pw", array(
        ':user_pw' => $user_pw
    ));

    foreach ($result as $item) {
        $counter++;
    }

    if ($counter == 1) {
        return true;
    } else {
        return false;
    }
}

//Diese Funktion sucht sich anhand der aktuellen Fragen-ID die nächste Frage aus der DB und gibt diese zurück. Sollte
//keine Frage mehr folgen, wird eine -1 zurückgegeben.
function survey_get_questions($current_question_id)
{

    $questions = array();
    $question_result = db_query("SELECT * FROM {question} ORDER BY question_id");

    foreach ($question_result as $question) {
        array_push($questions, $question->question_id);
    }

    $question_index = array_search($current_question_id, $questions);

    if (sizeof($questions) > $question_index) {
        return $questions[$question_index];
    } else {
        return -1;
    }
}
